# Generated by Django 5.1 on 2025-01-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_booked_appointment_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='end_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctorregistration',
            name='start_time',
            field=models.PositiveIntegerField(),
        ),
    ]
