# Generated by Django 5.1 on 2025-01-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_doctorregistration_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_slot',
            name='slot_houre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
