# Generated by Django 5.1 on 2025-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_doctor_slot_slot_houre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='token',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
