# Generated by Django 5.1 on 2025-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_registration_is_verified_registration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
