# Generated by Django 5.1 on 2025-03-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_doctorregistration_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='userRole',
            field=models.TextField(default='Doctor'),
        ),
        migrations.AddField(
            model_name='registration',
            name='userRole',
            field=models.TextField(default='User'),
        ),
    ]
