# Generated by Django 5.1 on 2025-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_doctorregistration_userrole_registration_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='Evening_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='Morning_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='Night_slot',
            field=models.BooleanField(default=False),
        ),
    ]
