# Generated by Django 5.1 on 2025-03-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_doctorregistration_evening_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_slot',
            old_name='slot_houre',
            new_name='slot_hour',
        ),
    ]
