# Generated by Django 5.1 on 2025-03-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_slot_houre_doctor_slot_slot_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='end_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorregistration',
            name='start_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
