# Generated by Django 5.1 on 2025-03-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_doctorregistration_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='end_time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='start_time',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
