# Generated by Django 5.1 on 2025-03-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_doctorregistration_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctorregistration',
            name='start_time',
            field=models.DateField(),
        ),
    ]
