# Generated by Django 5.1 on 2025-03-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_doctorregistration_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregistration',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctorregistration',
            name='start_time',
        ),
    ]
