# Generated by Django 5.1 on 2025-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_doctorregistration_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beds',
            name='Hospital_id',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
