# Generated by Django 5.1 on 2025-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_beds_hospital_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_status',
            name='Doctor_id',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
