# Generated by Django 5.1 on 2025-03-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_booking_status_doctor_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking_status',
            new_name='Booked_slot',
        ),
    ]
